# Generated by Django 3.1.7 on 2021-03-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='home',
            name='levels',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='home',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.area'),
            preserve_default=False,
        ),
    ]
